#!/usr/bin/env bash
# Displaying info about information about subdomains.
# Script: 0-world_wide_web

domain_information() {
    line=$(dig "$2"."$1" +short)
    if [ -n "$line" ]; then
        record_type=$(dig "$2"."$1" | awk 'NR==1 {print $4}')
        echo "The subdomain $2 is a $record_type record and points to $line"
    else
        echo "Error: Unable to retrieve information for $2.$1."
    fi
}

if [ "$#" == 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
fi

